### ISSUE TITLE
Hydrofabric file paths are not auto-populated

### ISSUE THREAD

**Issue by shahab122** [CIROH-UA/NGIAB-CloudInfra#138]
The hydrofabric (datastream.gpkg) file path is not auto-populated to define the catchment and nexus geojson files while running NGIAB. 

## Current behavior
The hydrofabric file paths for the catchment and nexus are empty (please see the screenshot below)

## Expected behavior
The file paths should be auto-populated as ./config/datastream.gpkg in both cases.

## Screenshots
![image](https://github.com/CIROH-UA/NGIAB-CloudInfra/assets/28275758/0848d1b6-615c-4bac-b2d8-e797d8285290)

**Comment by benlee0423** [comment]
@shahab122 
I have fixed the issue.
The root cause of the issue is the image for x86 is too old, and does not have recent changes we made.
And, the input file AWI_09_004 needs output specified.
Both are fixed now.
Here is instruction you can try.
1. Remove any existing input file AWI_09_004 and directories.
2. Remove existing docker image by running the following command.
`docker image rm <<IMAGE ID>>`
You can get the image id by running the following command.
`docker image ls`, search for image awiciroh/ciroh-ngen-image  with tag name latest-x86.
3. Download input file and untar
```
wget --no-parent https://ciroh-ua-ngen-data.s3.us-east-2.amazonaws.com/AWI-004/AWI_09_004.tar.gz
tar -xf AWI_09_004.tar.gz
```
5. Clone the NGIAB repo
`git clone https://github.com/CIROH-UA/NGIAB-CloudInfra.git`
6. Go to NGIAB-CloudInfra directory, and run `./guide.sh`

**Comment by benlee0423** [comment]
Finished 24 timesteps.
NGen top-level timings:
	NGen::init: 200.298
	NGen::simulation: 29.636
	NGen::routing: 4.039e-06

real	3m51.644s
user	7m5.769s
sys	0m29.571s
Finished executing command successfully.
Would you like to continue?
Select an option (type a number): 
1) Interactive-Shell
2) Exit
#? 1
Starting a shell, simply exit to stop the process.
bash-5.1# ls /ngen/ngen/data/outputs/ | wc -l
17231
bash-5.1# exit
exit
17231 new outputs created.
Any copied files can be found here: /home/ubuntu/temp/AWI_09_004/outputs
Thank you for running NextGen In A Box: National Water Model! Have a nice day!

**Comment by shahab122** [comment]
@benlee0423 the file paths are still not auto-populated for other case study data. Please see the screenshot: 
![image](https://github.com/CIROH-UA/NGIAB-CloudInfra/assets/28275758/36c898e8-ca72-4d23-aa2e-86a302a8201d)

**Comment by benlee0423** [comment]
I think you docker image still old one.
Please remove docker image in the machine completely,
```
docker image rm <<IMAGE ID>>
```
Then, try again.

**Comment by benlee0423** [comment]
Please do 
```
docker image ls
```
Paste the result here. It will tell how old your image is.

**Comment by benlee0423** [comment]
Remove the one on top, latest-x86 image, and try guide.sh again.
You have to select option 2
```
Run NextGen after updating to latest docker image
```
And, make sure it download latest-x86 image in the terminal.

**Comment by shahab122** [comment]
Tried to remove but got this:
sudo docker image rm 92bd8f22da46
Error response from daemon: conflict: unable to delete 92bd8f22da46 (cannot be forced) - image is being used by running container 45e42733f3be

**Comment by benlee0423** [comment]
sudo docker rm -f 92bd8f22da46

**Comment by shahab122** [comment]
Getting the same error response

**Comment by benlee0423** [comment]
This is due to @shahab122 used different input file that was not supported.

**Comment by shahab122** [comment]
@benlee0423 thanks for helping me to figure out this.
